/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.team;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-09 22:06:37
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class TeamVO extends SuperVO {
	private String pk_corp;
	private String pk_director;
	private Integer dr;
	private String voperatorid;
	private String team_director_name;
	private String team_name;
	private String ts;
	private String pk_team;

	public static final String PK_CORP = "pk_corp";
	public static final String PK_DIRECTOR = "pk_director";
	public static final String VOPERATORID = "voperatorid";
	public static final String TEAM_DIRECTOR_NAME = "team_director_name";
	public static final String TEAM_NAME = "team_name";
	public static final String PK_TEAM = "pk_team";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性pk_director的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return String
	 */
	public String getPk_director () {
		return pk_director;
	}   
	/**
	 * 属性pk_director的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newPk_director String
	 */
	public void setPk_director (String newPk_director ) {
	 	this.pk_director = newPk_director;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性team_director_name的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return String
	 */
	public String getTeam_director_name () {
		return team_director_name;
	}   
	/**
	 * 属性team_director_name的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newTeam_director_name String
	 */
	public void setTeam_director_name (String newTeam_director_name ) {
	 	this.team_director_name = newTeam_director_name;
	} 	  
	/**
	 * 属性team_name的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return String
	 */
	public String getTeam_name () {
		return team_name;
	}   
	/**
	 * 属性team_name的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newTeam_name String
	 */
	public void setTeam_name (String newTeam_name ) {
	 	this.team_name = newTeam_name;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性pk_team的Getter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @return String
	 */
	public String getPk_team () {
		return pk_team;
	}   
	/**
	 * 属性pk_team的Setter方法.
	 * 创建日期:2013-09-09 22:06:37
	 * @param newPk_team String
	 */
	public void setPk_team (String newPk_team ) {
	 	this.pk_team = newPk_team;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-09 22:06:37
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-09 22:06:37
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_team";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-09 22:06:37
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SMP_TEAM";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-09 22:06:37
	  */
     public TeamVO() {
		super();	
	}    
} 
