/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.partner;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-09 22:06:22
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PartnerVO extends SuperVO {
	private String pk_corp;
	private String pk_team;
	private String pk_partner;
	private Integer dr;
	private String voperatorid;
	private String ts;
	private String partner_name;
	public static final String PK_TEAM = "pk_team";
	public static final String PK_CORP = "pk_corp";
	public static final String PK_PARTNER = "pk_partner";
	public static final String VOPERATORID = "voperatorid";
	public static final String PARTNER_NAME = "partner_name";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	public String getPk_team () {
		return pk_team;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @param newPk_corp String
	 */
	public void setPk_team (String newPk_team ) {
	 	this.pk_team = newPk_team;
	} 	  
	/**
	 * 属性pk_partner的Getter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @return String
	 */
	public String getPk_partner () {
		return pk_partner;
	}   
	/**
	 * 属性pk_partner的Setter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @param newPk_partner String
	 */
	public void setPk_partner (String newPk_partner ) {
	 	this.pk_partner = newPk_partner;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性partner_name的Getter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @return String
	 */
	public String getPartner_name () {
		return partner_name;
	}   
	/**
	 * 属性partner_name的Setter方法.
	 * 创建日期:2013-09-09 22:06:22
	 * @param newPartner_name String
	 */
	public void setPartner_name (String newPartner_name ) {
	 	this.partner_name = newPartner_name;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-09 22:06:22
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-09 22:06:22
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_partner";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-09 22:06:22
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SMP_PARTNER";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-09 22:06:22
	  */
     public PartnerVO() {
		super();	
	}    
} 
