/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.coursetype;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-08-25 14:47:08
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CourseTypeVO extends SuperVO {
	private java.lang.String pk_coursetype;
	private java.lang.String coursetype_name;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_COURSETYPE = "pk_coursetype";
	public static final String COURSETYPE_NAME = "coursetype_name";
			
	/**
	 * 属性pk_coursetype的Getter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @return java.lang.String
	 */
	public java.lang.String getPk_coursetype () {
		return pk_coursetype;
	}   
	/**
	 * 属性pk_coursetype的Setter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @param newPk_coursetype java.lang.String
	 */
	public void setPk_coursetype (java.lang.String newPk_coursetype ) {
	 	this.pk_coursetype = newPk_coursetype;
	} 	  
	/**
	 * 属性coursetype_name的Getter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @return java.lang.String
	 */
	public java.lang.String getCoursetype_name () {
		return coursetype_name;
	}   
	/**
	 * 属性coursetype_name的Setter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @param newCoursetype_name java.lang.String
	 */
	public void setCoursetype_name (java.lang.String newCoursetype_name ) {
	 	this.coursetype_name = newCoursetype_name;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-08-25 14:47:08
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-08-25 14:47:08
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-08-25 14:47:08
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_coursetype";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-08-25 14:47:08
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "smp_coursetype";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-08-25 14:47:08
	  */
     public CourseTypeVO() {
		super();	
	}    
} 
