/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.parter;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-08-25 15:44:26
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class ParterVO extends SuperVO {
	private java.lang.String pk_parter;
	private java.lang.String parter_name;
	private java.lang.String pk_team;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_PARTER = "pk_parter";
	public static final String PARTER_NAME = "parter_name";
	public static final String PK_TEAM = "pk_team";
			
	/**
	 * 属性pk_parter的Getter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parter () {
		return pk_parter;
	}   
	/**
	 * 属性pk_parter的Setter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @param newPk_parter java.lang.String
	 */
	public void setPk_parter (java.lang.String newPk_parter ) {
	 	this.pk_parter = newPk_parter;
	} 	  
	/**
	 * 属性parter_name的Getter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @return java.lang.String
	 */
	public java.lang.String getParter_name () {
		return parter_name;
	}   
	/**
	 * 属性parter_name的Setter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @param newParter_name java.lang.String
	 */
	public void setParter_name (java.lang.String newParter_name ) {
	 	this.parter_name = newParter_name;
	} 	  
	/**
	 * 属性pk_team的Getter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @return java.lang.String
	 */
	public java.lang.String getPk_team () {
		return pk_team;
	}   
	/**
	 * 属性pk_team的Setter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @param newPk_team java.lang.String
	 */
	public void setPk_team (java.lang.String newPk_team ) {
	 	this.pk_team = newPk_team;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-08-25 15:44:26
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-08-25 15:44:26
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-08-25 15:44:26
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_parter";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-08-25 15:44:26
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "smp_parter";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-08-25 15:44:26
	  */
     public ParterVO() {
		super();	
	}    
} 
