/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.performance;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-10 21:36:33
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class PerformanceVO extends SuperVO {
	private String pk_partner;
	private UFDate performance_date;
	private String director_id;
	private String voperatorid;
	private Integer achievetype;
	private String pk_course;
	private String ts;
	private String pk_corp;
	private String remit_company;
	private String pk_performance;
	private Integer dr;
	private String remit_name;
	private String crm_remit_number;
	private UFDouble remit_amount;
	private String pk_team;

	public static final String PK_PARTNER = "pk_partner";
	public static final String PERFORMANCE_DATE = "performance_date";
	public static final String DIRECTOR_ID = "director_id";
	public static final String VOPERATORID = "voperatorid";
	public static final String ACHIEVETYPE = "achievetype";
	public static final String PK_COURSE = "pk_course";
	public static final String PK_CORP = "pk_corp";
	public static final String REMIT_COMPANY = "remit_company";
	public static final String PK_PERFORMANCE = "pk_performance";
	public static final String REMIT_NAME = "remit_name";
	public static final String CRM_REMIT_NUMBER = "crm_remit_number";
	public static final String REMIT_AMOUNT = "remit_amount";
	public static final String PK_TEAM = "pk_team";
			
	/**
	 * 属性pk_partner的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getPk_partner () {
		return pk_partner;
	}   
	/**
	 * 属性pk_partner的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newPk_partner String
	 */
	public void setPk_partner (String newPk_partner ) {
	 	this.pk_partner = newPk_partner;
	} 	  
	/**
	 * 属性performance_date的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public UFDate getPerformance_date () {
		return performance_date;
	}   
	/**
	 * 属性performance_date的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newPerformance_date String
	 */
	public void setPerformance_date (UFDate newPerformance_date ) {
	 	this.performance_date = newPerformance_date;
	} 	  
	/**
	 * 属性director_id的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getDirector_id () {
		return director_id;
	}   
	/**
	 * 属性director_id的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newDirector_id String
	 */
	public void setDirector_id (String newDirector_id ) {
	 	this.director_id = newDirector_id;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性achievetype的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return Integer
	 */
	public Integer getAchievetype () {
		return achievetype;
	}   
	/**
	 * 属性achievetype的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newAchievetype Integer
	 */
	public void setAchievetype (Integer newAchievetype ) {
	 	this.achievetype = newAchievetype;
	} 	  
	/**
	 * 属性pk_course的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getPk_course () {
		return pk_course;
	}   
	/**
	 * 属性pk_course的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newPk_course String
	 */
	public void setPk_course (String newPk_course ) {
	 	this.pk_course = newPk_course;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性remit_company的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getRemit_company () {
		return remit_company;
	}   
	/**
	 * 属性remit_company的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newRemit_company String
	 */
	public void setRemit_company (String newRemit_company ) {
	 	this.remit_company = newRemit_company;
	} 	  
	/**
	 * 属性pk_performance的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getPk_performance () {
		return pk_performance;
	}   
	/**
	 * 属性pk_performance的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newPk_performance String
	 */
	public void setPk_performance (String newPk_performance ) {
	 	this.pk_performance = newPk_performance;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性remit_name的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getRemit_name () {
		return remit_name;
	}   
	/**
	 * 属性remit_name的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newRemit_name String
	 */
	public void setRemit_name (String newRemit_name ) {
	 	this.remit_name = newRemit_name;
	} 	  
	/**
	 * 属性crm_remit_number的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getCrm_remit_number () {
		return crm_remit_number;
	}   
	/**
	 * 属性crm_remit_number的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newCrm_remit_number String
	 */
	public void setCrm_remit_number (String newCrm_remit_number ) {
	 	this.crm_remit_number = newCrm_remit_number;
	} 	  
	/**
	 * 属性remit_amount的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return UFDouble
	 */
	public UFDouble getRemit_amount () {
		return remit_amount;
	}   
	/**
	 * 属性remit_amount的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newRemit_amount UFDouble
	 */
	public void setRemit_amount (UFDouble newRemit_amount ) {
	 	this.remit_amount = newRemit_amount;
	} 	  
	/**
	 * 属性pk_team的Getter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @return String
	 */
	public String getPk_team () {
		return pk_team;
	}   
	/**
	 * 属性pk_team的Setter方法.
	 * 创建日期:2013-09-10 21:36:33
	 * @param newPk_team String
	 */
	public void setPk_team (String newPk_team ) {
	 	this.pk_team = newPk_team;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-10 21:36:33
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-10 21:36:33
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_performance";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-10 21:36:33
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SMP_PERFORMANCE";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-10 21:36:33
	  */
     public PerformanceVO() {
		super();	
	}    
} 
