/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.tuikuan;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-04 21:14:42
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class TuiKuanVO extends SuperVO {
	private java.lang.String pk_tuikuan;
	private java.lang.String pk_refund;
	private nc.vo.pub.lang.UFDouble amount;
	private java.lang.String reason;
	private java.lang.String approved_by;
	private java.lang.String approved_status;
	private java.lang.String approve_date;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_TUIKUAN = "pk_tuikuan";
	public static final String PK_REFUND = "pk_refund";
	public static final String AMOUNT = "amount";
	public static final String REASON = "reason";
	public static final String APPROVED_BY = "approved_by";
	public static final String APPROVED_STATUS = "approved_status";
	public static final String APPROVE_DATE = "approve_date";
			
	/**
	 * 属性pk_tuikuan的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.String
	 */
	public java.lang.String getPk_tuikuan () {
		return pk_tuikuan;
	}   
	/**
	 * 属性pk_tuikuan的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newPk_tuikuan java.lang.String
	 */
	public void setPk_tuikuan (java.lang.String newPk_tuikuan ) {
	 	this.pk_tuikuan = newPk_tuikuan;
	} 	  
	/**
	 * 属性pk_refund的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.String
	 */
	public java.lang.String getPk_refund () {
		return pk_refund;
	}   
	/**
	 * 属性pk_refund的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newPk_refund java.lang.String
	 */
	public void setPk_refund (java.lang.String newPk_refund ) {
	 	this.pk_refund = newPk_refund;
	} 	  
	/**
	 * 属性amount的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getAmount () {
		return amount;
	}   
	/**
	 * 属性amount的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newAmount nc.vo.pub.lang.UFDouble
	 */
	public void setAmount (nc.vo.pub.lang.UFDouble newAmount ) {
	 	this.amount = newAmount;
	} 	  
	/**
	 * 属性reason的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.String
	 */
	public java.lang.String getReason () {
		return reason;
	}   
	/**
	 * 属性reason的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newReason java.lang.String
	 */
	public void setReason (java.lang.String newReason ) {
	 	this.reason = newReason;
	} 	  
	/**
	 * 属性approved_by的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.String
	 */
	public java.lang.String getApproved_by () {
		return approved_by;
	}   
	/**
	 * 属性approved_by的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newApproved_by java.lang.String
	 */
	public void setApproved_by (java.lang.String newApproved_by ) {
	 	this.approved_by = newApproved_by;
	} 	  
	/**
	 * 属性approved_status的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.String
	 */
	public java.lang.String getApproved_status () {
		return approved_status;
	}   
	/**
	 * 属性approved_status的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newApproved_status java.lang.String
	 */
	public void setApproved_status (java.lang.String newApproved_status ) {
	 	this.approved_status = newApproved_status;
	} 	  
	/**
	 * 属性approve_date的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.String
	 */
	public java.lang.String getApprove_date () {
		return approve_date;
	}   
	/**
	 * 属性approve_date的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newApprove_date java.lang.String
	 */
	public void setApprove_date (java.lang.String newApprove_date ) {
	 	this.approve_date = newApprove_date;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-04 21:14:42
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-04 21:14:42
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-04 21:14:42
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_tuikuan";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-04 21:14:42
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "smp_tuikuan";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-04 21:14:42
	  */
     public TuiKuanVO() {
		super();	
	}    
} 
