/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.area;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-07 17:38:54
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class AreaVO extends SuperVO {
	private String pk_corp;
	private String vbillno;
	private String vbusicode;
	private Integer dr;
	private String voperatorid;
	private String vapprovenote;
	private UFDate dapprovedate;
	private Integer vbillstatus;
	private String vapproveid;
	private String pk_area;
	private String pk_busitype;
	private nc.vo.pub.lang.UFDateTime ts;
	private String name;

	public static final String PK_CORP = "pk_corp";
	public static final String VBILLNO = "vbillno";
	public static final String VBUSICODE = "vbusicode";
	public static final String VOPERATORID = "voperatorid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String VAPPROVEID = "vapproveid";
	public static final String PK_AREA = "pk_area";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String NAME = "name";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性vbusicode的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getVbusicode () {
		return vbusicode;
	}   
	/**
	 * 属性vbusicode的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newVbusicode String
	 */
	public void setVbusicode (String newVbusicode ) {
	 	this.vbusicode = newVbusicode;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return Integer
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newVbillstatus Integer
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性pk_area的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getPk_area () {
		return pk_area;
	}   
	/**
	 * 属性pk_area的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newPk_area String
	 */
	public void setPk_area (String newPk_area ) {
	 	this.pk_area = newPk_area;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newTs String
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @return String
	 */
	public String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:2013-09-07 17:38:54
	 * @param newName String
	 */
	public void setName (String newName ) {
	 	this.name = newName;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-07 17:38:54
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-07 17:38:54
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_area";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-07 17:38:54
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SMP_AREA";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-07 17:38:54
	  */
     public AreaVO() {
		super();	
	}    
} 
