/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-07 18:42:08
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class REFUNDVO extends SuperVO {
	private String pk_corp;
	private String refundid;
	private UFDateTime ts;
	private String refundreason;
	private String pk_performance;
	private String voperatorid;
	private String vapprovenote;
	private String refundamount;
	private UFDouble vbillstatus;
	private String vapproveid;
	private String vbusicode;
	private UFDate dapprovedate;
	private String vbillno;
	private String pk_busitype;
	private UFDouble dr;

	public static final String PK_CORP = "pk_corp";
	public static final String REFUNDID = "refundid";
	public static final String REFUNDREASON = "refundreason";
	public static final String PK_PERFORMANCE = "pk_performance";
	public static final String VOPERATORID = "voperatorid";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String REFUNDAMOUNT = "refundamount";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String VAPPROVEID = "vapproveid";
	public static final String VBUSICODE = "vbusicode";
	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String VBILLNO = "vbillno";
	public static final String PK_BUSITYPE = "pk_busitype";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性refundid的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getRefundid () {
		return refundid;
	}   
	/**
	 * 属性refundid的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newRefundid String
	 */
	public void setRefundid (String newRefundid ) {
	 	this.refundid = newRefundid;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性refundreason的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getRefundreason () {
		return refundreason;
	}   
	/**
	 * 属性refundreason的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newRefundreason String
	 */
	public void setRefundreason (String newRefundreason ) {
	 	this.refundreason = newRefundreason;
	} 	  
	/**
	 * 属性pk_performance的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getPk_performance () {
		return pk_performance;
	}   
	/**
	 * 属性pk_performance的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newPk_performance String
	 */
	public void setPk_performance (String newPk_performance ) {
	 	this.pk_performance = newPk_performance;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性refundamount的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getRefundamount () {
		return refundamount;
	}   
	/**
	 * 属性refundamount的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newRefundamount String
	 */
	public void setRefundamount (String newRefundamount ) {
	 	this.refundamount = newRefundamount;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return UFDouble
	 */
	public UFDouble getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newVbillstatus UFDouble
	 */
	public void setVbillstatus (UFDouble newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性vbusicode的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getVbusicode () {
		return vbusicode;
	}   
	/**
	 * 属性vbusicode的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newVbusicode String
	 */
	public void setVbusicode (String newVbusicode ) {
	 	this.vbusicode = newVbusicode;
	} 	  
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @return UFDouble
	 */
	public UFDouble getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-07 18:42:08
	 * @param newDr UFDouble
	 */
	public void setDr (UFDouble newDr ) {
	 	this.dr = newDr;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-07 18:42:08
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-07 18:42:08
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "refundid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-07 18:42:08
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "T_REFUND";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-07 18:42:08
	  */
     public REFUNDVO() {
		super();	
	}    
} 
