/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.team;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-08-25 15:46:19
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class TeamVO extends SuperVO {
	private java.lang.String pk_team;
	private java.lang.String team_name;
	private java.lang.String team_director;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_TEAM = "pk_team";
	public static final String TEAM_NAME = "team_name";
	public static final String TEAM_DIRECTOR = "team_director";
			
	/**
	 * 属性pk_team的Getter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @return java.lang.String
	 */
	public java.lang.String getPk_team () {
		return pk_team;
	}   
	/**
	 * 属性pk_team的Setter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @param newPk_team java.lang.String
	 */
	public void setPk_team (java.lang.String newPk_team ) {
	 	this.pk_team = newPk_team;
	} 	  
	/**
	 * 属性team_name的Getter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @return java.lang.String
	 */
	public java.lang.String getTeam_name () {
		return team_name;
	}   
	/**
	 * 属性team_name的Setter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @param newTeam_name java.lang.String
	 */
	public void setTeam_name (java.lang.String newTeam_name ) {
	 	this.team_name = newTeam_name;
	} 	  
	/**
	 * 属性team_director的Getter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @return java.lang.String
	 */
	public java.lang.String getTeam_director () {
		return team_director;
	}   
	/**
	 * 属性team_director的Setter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @param newTeam_director java.lang.String
	 */
	public void setTeam_director (java.lang.String newTeam_director ) {
	 	this.team_director = newTeam_director;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-08-25 15:46:19
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-08-25 15:46:19
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-08-25 15:46:19
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_team";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-08-25 15:46:19
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "smp_team";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-08-25 15:46:19
	  */
     public TeamVO() {
		super();	
	}    
} 
