/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.refund;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-08-25 15:51:11
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class RefundVO extends SuperVO {
	private java.lang.String pk_refund;
	private nc.vo.pub.lang.UFDate performance_date;
	private java.lang.String pk_course;
	private java.lang.String remit_company;
	private java.lang.String remit_name;
	private java.lang.String remit_amount;
	private java.lang.String pk_parter;
	private java.lang.String pk_team;
	private java.lang.String pk_director;
	private java.lang.String crm_remit_number;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_REFUND = "pk_refund";
	public static final String PERFORMANCE_DATE = "performance_date";
	public static final String PK_COURSE = "pk_course";
	public static final String REMIT_COMPANY = "remit_company";
	public static final String REMIT_NAME = "remit_name";
	public static final String REMIT_AMOUNT = "remit_amount";
	public static final String PK_PARTER = "pk_parter";
	public static final String PK_TEAM = "pk_team";
	public static final String PK_DIRECTOR = "pk_director";
	public static final String CRM_REMIT_NUMBER = "crm_remit_number";
			
	/**
	 * 属性pk_refund的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getPk_refund () {
		return pk_refund;
	}   
	/**
	 * 属性pk_refund的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newPk_refund java.lang.String
	 */
	public void setPk_refund (java.lang.String newPk_refund ) {
	 	this.pk_refund = newPk_refund;
	} 	  
	/**
	 * 属性performance_date的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getPerformance_date () {
		return performance_date;
	}   
	/**
	 * 属性performance_date的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newPerformance_date nc.vo.pub.lang.UFDate
	 */
	public void setPerformance_date (nc.vo.pub.lang.UFDate newPerformance_date ) {
	 	this.performance_date = newPerformance_date;
	} 	  
	/**
	 * 属性pk_course的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getPk_course () {
		return pk_course;
	}   
	/**
	 * 属性pk_course的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newPk_course java.lang.String
	 */
	public void setPk_course (java.lang.String newPk_course ) {
	 	this.pk_course = newPk_course;
	} 	  
	/**
	 * 属性remit_company的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getRemit_company () {
		return remit_company;
	}   
	/**
	 * 属性remit_company的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newRemit_company java.lang.String
	 */
	public void setRemit_company (java.lang.String newRemit_company ) {
	 	this.remit_company = newRemit_company;
	} 	  
	/**
	 * 属性remit_name的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getRemit_name () {
		return remit_name;
	}   
	/**
	 * 属性remit_name的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newRemit_name java.lang.String
	 */
	public void setRemit_name (java.lang.String newRemit_name ) {
	 	this.remit_name = newRemit_name;
	} 	  
	/**
	 * 属性remit_amount的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getRemit_amount () {
		return remit_amount;
	}   
	/**
	 * 属性remit_amount的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newRemit_amount java.lang.String
	 */
	public void setRemit_amount (java.lang.String newRemit_amount ) {
	 	this.remit_amount = newRemit_amount;
	} 	  
	/**
	 * 属性pk_parter的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getPk_parter () {
		return pk_parter;
	}   
	/**
	 * 属性pk_parter的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newPk_parter java.lang.String
	 */
	public void setPk_parter (java.lang.String newPk_parter ) {
	 	this.pk_parter = newPk_parter;
	} 	  
	/**
	 * 属性pk_team的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getPk_team () {
		return pk_team;
	}   
	/**
	 * 属性pk_team的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newPk_team java.lang.String
	 */
	public void setPk_team (java.lang.String newPk_team ) {
	 	this.pk_team = newPk_team;
	} 	  
	/**
	 * 属性pk_director的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getPk_director () {
		return pk_director;
	}   
	/**
	 * 属性pk_director的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newPk_director java.lang.String
	 */
	public void setPk_director (java.lang.String newPk_director ) {
	 	this.pk_director = newPk_director;
	} 	  
	/**
	 * 属性crm_remit_number的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getCrm_remit_number () {
		return crm_remit_number;
	}   
	/**
	 * 属性crm_remit_number的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newCrm_remit_number java.lang.String
	 */
	public void setCrm_remit_number (java.lang.String newCrm_remit_number ) {
	 	this.crm_remit_number = newCrm_remit_number;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-08-25 15:51:11
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-08-25 15:51:11
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-08-25 15:51:11
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_refund";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-08-25 15:51:11
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "smp_refund";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-08-25 15:51:11
	  */
     public RefundVO() {
		super();	
	}    
} 
