/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.coursetype;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-09 22:06:04
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CourseTypeVO extends SuperVO {
	private String pk_corp;
	private String coursetypename;
	private Integer dr;
	private String voperatorid;
	private String pk_coursetype;
	private String ts;
	private String vbusicode;

	public static final String PK_CORP = "pk_corp";
	public static final String COURSETYPENAME = "coursetypename";
	public static final String VOPERATORID = "voperatorid";
	public static final String PK_COURSETYPE = "pk_coursetype";
	public static final String VBUSICODE = "vbusicode";
			
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性coursetypename的Getter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @return String
	 */
	public String getCoursetypename () {
		return coursetypename;
	}   
	/**
	 * 属性coursetypename的Setter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @param newCoursetypename String
	 */
	public void setCoursetypename (String newCoursetypename ) {
	 	this.coursetypename = newCoursetypename;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性pk_coursetype的Getter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @return String
	 */
	public String getPk_coursetype () {
		return pk_coursetype;
	}   
	/**
	 * 属性pk_coursetype的Setter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @param newPk_coursetype String
	 */
	public void setPk_coursetype (String newPk_coursetype ) {
	 	this.pk_coursetype = newPk_coursetype;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vbusicode的Getter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @return String
	 */
	public String getVbusicode () {
		return vbusicode;
	}   
	/**
	 * 属性vbusicode的Setter方法.
	 * 创建日期:2013-09-09 22:06:04
	 * @param newVbusicode String
	 */
	public void setVbusicode (String newVbusicode ) {
	 	this.vbusicode = newVbusicode;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-09 22:06:04
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-09 22:06:04
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_coursetype";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-09 22:06:04
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SMP_COURSETYPE";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-09 22:06:04
	  */
     public CourseTypeVO() {
		super();	
	}    
} 
