/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.course;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-09 22:05:40
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class CourseVO extends SuperVO {
	private String course_name;
	private String reserverd5;
	private String voperatorid;
	private String reserved3;
	private UFDouble headerquarter_percentage;
	private String remark;
	private String reserved2;
	private String course_code;
	private String pk_coursetype;
	private String reserved1;
	private String pk_course;
	private String ts;
	private String vbusicode;
	private String reserved4;
	private UFDouble jixiao_percentage;
	private String pk_corp;
	private UFDouble branch_percentage;
	private UFDouble agency_percentage;
	private Integer dr;
	private UFDouble shidao_percentage;

	public static final String COURSE_NAME = "course_name";
	public static final String RESERVERD5 = "reserverd5";
	public static final String VOPERATORID = "voperatorid";
	public static final String RESERVED3 = "reserved3";
	public static final String HEADERQUARTER_PERCENTAGE = "headerquarter_percentage";
	public static final String REMARK = "remark";
	public static final String RESERVED2 = "reserved2";
	public static final String COURSE_CODE = "course_code";
	public static final String PK_COURSETYPE = "pk_coursetype";
	public static final String RESERVED1 = "reserved1";
	public static final String PK_COURSE = "pk_course";
	public static final String VBUSICODE = "vbusicode";
	public static final String RESERVED4 = "reserved4";
	public static final String JIXIAO_PERCENTAGE = "jixiao_percentage";
	public static final String PK_CORP = "pk_corp";
	public static final String BRANCH_PERCENTAGE = "branch_percentage";
	public static final String AGENCY_PERCENTAGE = "agency_percentage";
	public static final String SHIDAO_PERCENTAGE = "shidao_percentage";
			
	/**
	 * 属性course_name的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getCourse_name () {
		return course_name;
	}   
	/**
	 * 属性course_name的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newCourse_name String
	 */
	public void setCourse_name (String newCourse_name ) {
	 	this.course_name = newCourse_name;
	} 	  
	/**
	 * 属性reserverd5的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getReserverd5 () {
		return reserverd5;
	}   
	/**
	 * 属性reserverd5的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newReserverd5 String
	 */
	public void setReserverd5 (String newReserverd5 ) {
	 	this.reserverd5 = newReserverd5;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性reserved3的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getReserved3 () {
		return reserved3;
	}   
	/**
	 * 属性reserved3的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newReserved3 String
	 */
	public void setReserved3 (String newReserved3 ) {
	 	this.reserved3 = newReserved3;
	} 	  
	/**
	 * 属性headerquarter_percentage的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return UFDouble
	 */
	public UFDouble getHeaderquarter_percentage () {
		return headerquarter_percentage;
	}   
	/**
	 * 属性headerquarter_percentage的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newHeaderquarter_percentage UFDouble
	 */
	public void setHeaderquarter_percentage (UFDouble newHeaderquarter_percentage ) {
	 	this.headerquarter_percentage = newHeaderquarter_percentage;
	} 	  
	/**
	 * 属性remark的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getRemark () {
		return remark;
	}   
	/**
	 * 属性remark的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newRemark String
	 */
	public void setRemark (String newRemark ) {
	 	this.remark = newRemark;
	} 	  
	/**
	 * 属性reserved2的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getReserved2 () {
		return reserved2;
	}   
	/**
	 * 属性reserved2的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newReserved2 String
	 */
	public void setReserved2 (String newReserved2 ) {
	 	this.reserved2 = newReserved2;
	} 	  
	/**
	 * 属性course_code的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getCourse_code () {
		return course_code;
	}   
	/**
	 * 属性course_code的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newCourse_code String
	 */
	public void setCourse_code (String newCourse_code ) {
	 	this.course_code = newCourse_code;
	} 	  
	/**
	 * 属性pk_coursetype的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getPk_coursetype () {
		return pk_coursetype;
	}   
	/**
	 * 属性pk_coursetype的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newPk_coursetype String
	 */
	public void setPk_coursetype (String newPk_coursetype ) {
	 	this.pk_coursetype = newPk_coursetype;
	} 	  
	/**
	 * 属性reserved1的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getReserved1 () {
		return reserved1;
	}   
	/**
	 * 属性reserved1的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newReserved1 String
	 */
	public void setReserved1 (String newReserved1 ) {
	 	this.reserved1 = newReserved1;
	} 	  
	/**
	 * 属性pk_course的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getPk_course () {
		return pk_course;
	}   
	/**
	 * 属性pk_course的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newPk_course String
	 */
	public void setPk_course (String newPk_course ) {
	 	this.pk_course = newPk_course;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vbusicode的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getVbusicode () {
		return vbusicode;
	}   
	/**
	 * 属性vbusicode的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newVbusicode String
	 */
	public void setVbusicode (String newVbusicode ) {
	 	this.vbusicode = newVbusicode;
	} 	  
	/**
	 * 属性reserved4的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getReserved4 () {
		return reserved4;
	}   
	/**
	 * 属性reserved4的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newReserved4 String
	 */
	public void setReserved4 (String newReserved4 ) {
	 	this.reserved4 = newReserved4;
	} 	  
	/**
	 * 属性jixiao_percentage的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return UFDouble
	 */
	public UFDouble getJixiao_percentage () {
		return jixiao_percentage;
	}   
	/**
	 * 属性jixiao_percentage的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newJixiao_percentage UFDouble
	 */
	public void setJixiao_percentage (UFDouble newJixiao_percentage ) {
	 	this.jixiao_percentage = newJixiao_percentage;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性branch_percentage的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return UFDouble
	 */
	public UFDouble getBranch_percentage () {
		return branch_percentage;
	}   
	/**
	 * 属性branch_percentage的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newBranch_percentage UFDouble
	 */
	public void setBranch_percentage (UFDouble newBranch_percentage ) {
	 	this.branch_percentage = newBranch_percentage;
	} 	  
	/**
	 * 属性agency_percentage的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return UFDouble
	 */
	public UFDouble getAgency_percentage () {
		return agency_percentage;
	}   
	/**
	 * 属性agency_percentage的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newAgency_percentage UFDouble
	 */
	public void setAgency_percentage (UFDouble newAgency_percentage ) {
	 	this.agency_percentage = newAgency_percentage;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性shidao_percentage的Getter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @return UFDouble
	 */
	public UFDouble getShidao_percentage () {
		return shidao_percentage;
	}   
	/**
	 * 属性shidao_percentage的Setter方法.
	 * 创建日期:2013-09-09 22:05:40
	 * @param newShidao_percentage UFDouble
	 */
	public void setShidao_percentage (UFDouble newShidao_percentage ) {
	 	this.shidao_percentage = newShidao_percentage;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-09 22:05:40
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-09 22:05:40
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_course";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-09 22:05:40
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SMP_COURSE";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-09 22:05:40
	  */
     public CourseVO() {
		super();	
	}    
} 
