/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.smp.clsexe;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2013-09-09 22:45:59
 * @author Administrator
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class ClsexeVO extends SuperVO {
	private UFDate dapprovedate;
	private String pk_corp;
	private String ts;
	private String vbusicode;
	private String pk_clsexe;
	private Integer sequence;
	private Integer studentnum;
	private String pk_busitype;
	private String vapproveid;
	private UFDate classdate;
	private String pk_area;
	private String vapprovenote;
	private Integer vbillstatus;
	private String voperatorid;
	private String vbillno;
	private Integer dr;
	private String name;
	private UFDouble money;
	private String pk_project;

	public static final String DAPPROVEDATE = "dapprovedate";
	public static final String PK_CORP = "pk_corp";
	public static final String VBUSICODE = "vbusicode";
	public static final String PK_CLSEXE = "pk_clsexe";
	public static final String SEQUENCE = "sequence";
	public static final String STUDENTNUM = "studentnum";
	public static final String PK_BUSITYPE = "pk_busitype";
	public static final String VAPPROVEID = "vapproveid";
	public static final String CLASSDATE = "classdate";
	public static final String PK_AREA = "pk_area";
	public static final String VAPPROVENOTE = "vapprovenote";
	public static final String VBILLSTATUS = "vbillstatus";
	public static final String VOPERATORID = "voperatorid";
	public static final String VBILLNO = "vbillno";
	public static final String NAME = "name";
	public static final String MONEY = "money";
	public static final String PK_PROJECT = "pk_project";
			
	/**
	 * 属性dapprovedate的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return UFDate
	 */
	public UFDate getDapprovedate () {
		return dapprovedate;
	}   
	/**
	 * 属性dapprovedate的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newDapprovedate UFDate
	 */
	public void setDapprovedate (UFDate newDapprovedate ) {
	 	this.dapprovedate = newDapprovedate;
	} 	  
	/**
	 * 属性pk_corp的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getPk_corp () {
		return pk_corp;
	}   
	/**
	 * 属性pk_corp的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newPk_corp String
	 */
	public void setPk_corp (String newPk_corp ) {
	 	this.pk_corp = newPk_corp;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newTs String
	 */
	public void setTs (String newTs ) {
	 	this.ts = newTs;
	} 	  
	/**
	 * 属性vbusicode的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getVbusicode () {
		return vbusicode;
	}   
	/**
	 * 属性vbusicode的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newVbusicode String
	 */
	public void setVbusicode (String newVbusicode ) {
	 	this.vbusicode = newVbusicode;
	} 	  
	/**
	 * 属性pk_clsexe的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getPk_clsexe () {
		return pk_clsexe;
	}   
	/**
	 * 属性pk_clsexe的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newPk_clsexe String
	 */
	public void setPk_clsexe (String newPk_clsexe ) {
	 	this.pk_clsexe = newPk_clsexe;
	} 	  
	/**
	 * 属性sequence的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return Integer
	 */
	public Integer getSequence () {
		return sequence;
	}   
	/**
	 * 属性sequence的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newSequence Integer
	 */
	public void setSequence (Integer newSequence ) {
	 	this.sequence = newSequence;
	} 	  
	/**
	 * 属性studentnum的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return Integer
	 */
	public Integer getStudentnum () {
		return studentnum;
	}   
	/**
	 * 属性studentnum的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newStudentnum Integer
	 */
	public void setStudentnum (Integer newStudentnum ) {
	 	this.studentnum = newStudentnum;
	} 	  
	/**
	 * 属性pk_busitype的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getPk_busitype () {
		return pk_busitype;
	}   
	/**
	 * 属性pk_busitype的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newPk_busitype String
	 */
	public void setPk_busitype (String newPk_busitype ) {
	 	this.pk_busitype = newPk_busitype;
	} 	  
	/**
	 * 属性vapproveid的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getVapproveid () {
		return vapproveid;
	}   
	/**
	 * 属性vapproveid的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newVapproveid String
	 */
	public void setVapproveid (String newVapproveid ) {
	 	this.vapproveid = newVapproveid;
	} 	  
	/**
	 * 属性classdate的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return UFDate
	 */
	public UFDate getClassdate () {
		return classdate;
	}   
	/**
	 * 属性classdate的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newClassdate UFDate
	 */
	public void setClassdate (UFDate newClassdate ) {
	 	this.classdate = newClassdate;
	} 	  
	/**
	 * 属性pk_area的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getPk_area () {
		return pk_area;
	}   
	/**
	 * 属性pk_area的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newPk_area String
	 */
	public void setPk_area (String newPk_area ) {
	 	this.pk_area = newPk_area;
	} 	  
	/**
	 * 属性vapprovenote的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getVapprovenote () {
		return vapprovenote;
	}   
	/**
	 * 属性vapprovenote的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newVapprovenote String
	 */
	public void setVapprovenote (String newVapprovenote ) {
	 	this.vapprovenote = newVapprovenote;
	} 	  
	/**
	 * 属性vbillstatus的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return Integer
	 */
	public Integer getVbillstatus () {
		return vbillstatus;
	}   
	/**
	 * 属性vbillstatus的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newVbillstatus Integer
	 */
	public void setVbillstatus (Integer newVbillstatus ) {
	 	this.vbillstatus = newVbillstatus;
	} 	  
	/**
	 * 属性voperatorid的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getVoperatorid () {
		return voperatorid;
	}   
	/**
	 * 属性voperatorid的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newVoperatorid String
	 */
	public void setVoperatorid (String newVoperatorid ) {
	 	this.voperatorid = newVoperatorid;
	} 	  
	/**
	 * 属性vbillno的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getVbillno () {
		return vbillno;
	}   
	/**
	 * 属性vbillno的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newVbillno String
	 */
	public void setVbillno (String newVbillno ) {
	 	this.vbillno = newVbillno;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return Integer
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newDr Integer
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性name的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getName () {
		return name;
	}   
	/**
	 * 属性name的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newName String
	 */
	public void setName (String newName ) {
	 	this.name = newName;
	} 	  
	/**
	 * 属性money的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return UFDouble
	 */
	public UFDouble getMoney () {
		return money;
	}   
	/**
	 * 属性money的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newMoney UFDouble
	 */
	public void setMoney (UFDouble newMoney ) {
	 	this.money = newMoney;
	} 	  
	/**
	 * 属性pk_project的Getter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @return String
	 */
	public String getPk_project () {
		return pk_project;
	}   
	/**
	 * 属性pk_project的Setter方法.
	 * 创建日期:2013-09-09 22:45:59
	 * @param newPk_project String
	 */
	public void setPk_project (String newPk_project ) {
	 	this.pk_project = newPk_project;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2013-09-09 22:45:59
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2013-09-09 22:45:59
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_clsexe";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2013-09-09 22:45:59
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SMP_CLSEXE";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2013-09-09 22:45:59
	  */
     public ClsexeVO() {
		super();	
	}    
} 
